c_compiler:  # [osx or win]
  - clang  # [osx]
  - vs2015  # [win]
  - vs2015  # [win]
  - vs2015  # [win]
cxx_compiler:  # [osx or win]
  - clangxx  # [osx]
  - vs2015  # [win]
  - vs2015  # [win]
  - vs2015  # [win]

python:  # [win]
  - 2.7  # [win]
  - 3.5  # [win]
  - 3.6  # [win]

vc:  # [win]
  - 14  # [win]
  - 14  # [win]
  - 14  # [win]
