{% set version = "3.11.1.0" %}
{% set sha256 = "9c6347584e778c5dcdd2dceb296b3e39f3374e38565c1133a88a68a7cac1ec41" %}
{% set build_number = "1" %}  # use for ease of rebasing other branches

package:
  name: uhd
  version: {{ version }}

source:
  url: https://github.com/EttusResearch/uhd/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: True  # [not py36] to avoid building pointlessly against multiple python
  run_exports:
    - {{ pin_subpackage('uhd', min_pin='x.x.x', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.8
    - jom  # [win]

  host:
    - boost
    - boost-cpp
    - libusb >=1
    - mako >=0.5.0
    - pkg-config  # [not win]
    - python
    - requests

  run:
    - {{ pin_compatible('boost', max_pin='x.x.x') }}  # needed until boost package has run_exports
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    # python >=2.7 is required, but requests pulls it in and leaving it out
    # means no automatic pinning (can be different version from build)
    #- python
    - requests

test:
  commands:
    # verify CLI tools
    {% set uhd_cmds = [
        "octoclock_firmware_burner",
        "uhd_cal_rx_iq_balance",
        "uhd_cal_tx_dc_offset",
        "uhd_cal_tx_iq_balance",
        "uhd_config_info",
        "uhd_find_devices",
        "uhd_image_loader",
        "uhd_usrp_probe",
        "usrp_n2xx_simple_net_burner",
        "usrp_x3xx_fpga_burner",
    ] %}
    {% for each_cmd in uhd_cmds %}
    - command -v {{ each_cmd }}  # [unix]
    - where {{ each_cmd }}  # [win]
    {% endfor %}

    # verify libraries
    {% set uhd_lib = "uhd" %}
    - test -f $PREFIX/lib/lib{{ uhd_lib }}${SHLIB_EXT}  # [unix]
    - conda inspect linkages -p $PREFIX uhd  # [not win]
    - conda inspect objects -p $PREFIX uhd  # [osx]

about:
  home: http://github.com/EttusResearch/uhd
  license: GPL-3.0
  license_file: host/LICENSE
  summary: 'Software driver and API for the Ettus Research USRP SDR platform'
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: http://files.ettus.com/manual/
  dev_url: http://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
