{% set version = "3.10.1.1" %}

package:
  name: uhd
  version: {{ version }}

source:
  url: http://files.ettus.com/binaries/uhd/src/uhd-{{ version }}.tar.gz
  sha256: b0c9b1c4e6691f61e13805b74c56d3261ee98c528e96a0992e169fdc24309178

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - pkg-config
    - cmake >=2.8
    - boost 1.64.*
    - python >=2.7
    - mako >=0.5.0
    - libusb >=1
    - doxygen

  run:
    - boost 1.64.*
    - python >=2.7
    - requests

about:
  home: http://github.com/EttusResearch/uhd
  license: GPL-3.0
  license_file: host/LICENSE
  summary: 'Software driver and API for the Ettus Research USRP SDR platform'
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: http://files.ettus.com/manual/
  dev_url: http://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
