{% set version = "3.10.2.0" %}
{% set padded_version = "003.010.002.000" %}
{% set sha256 = "dbb2bc42132212c59673c50a14718ad4a9c3d90cb035e836fdf08bf6fe95e33a" %}
{% set build_number = "0" %}


package:
  name: uhd
  version: {{ version }}

source:
  url: http://files.ettus.com/binaries/uhd/uhd_{{ padded_version }}-release/uhd-{{ version }}-release.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: True  # [win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - boost 1.64.*
    - cmake >=2.8
    - libusb >=1
    - mako >=0.5.0
    - pkg-config
    # need python >=2.7, but result is no different with any valid python
    # specify one version to get single build
    - python {{ PY_VER }}*
    - toolchain

  run:
    - boost 1.64.*
    - libusb >=1
    - python >=2.7
    - requests

test:
  commands:
    # verify CLI tools
    {% set uhd_cmds = [
        "octoclock_firmware_burner",
        "uhd_cal_rx_iq_balance",
        "uhd_cal_tx_dc_offset",
        "uhd_cal_tx_iq_balance",
        "uhd_config_info",
        "uhd_find_devices",
        "uhd_image_loader",
        "uhd_usrp_probe",
        "usrp_n2xx_simple_net_burner",
        "usrp_x3xx_fpga_burner",
    ] %}
    {% for each_cmd in uhd_cmds %}
    - command -v {{ each_cmd }}  # [unix]
    {% endfor %}

    # verify libraries
    {% set uhd_lib = "libuhd" %}
    - test -f $PREFIX/lib/{{ uhd_lib }}.dylib  # [osx]
    - otool -L $PREFIX/lib/{{ uhd_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ uhd_lib }}.so  # [linux]

about:
  home: http://github.com/EttusResearch/uhd
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Software driver and API for the Ettus Research USRP SDR platform'
  description: |
    UHD is the free & open-source software driver and API for the Universal
    Software Radio Peripheral (USRP(TM)) SDR platform, created and sold by
    Ettus Research. UHD supports all Ettus Research USRP(TM) hardware,
    including all motherboards and daughterboards, and the combinations thereof.
  doc_url: http://files.ettus.com/manual/
  dev_url: http://github.com/EttusResearch/uhd

extra:
  recipe-maintainers:
    - ryanvolz
